config/routes.rb
Rails.application.routes.draw do

  resources :pets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(strong_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(strong_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def strong_params
    params.require(:pet).permit(:name, :species, :found_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "Add a found Pet", new_pet_path %>
    <%= link_to "Back", pets_path %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="offset-sm-3 col-sm-6">
  <%= simple_form_for pet do |f| %>
    <%= f.input :name %>
    <%= f.input :species %>
    <%= f.input :found_date %>
    <% unless pet.new_record? %>
      <%= f.input :name %>
    <% end %>

    <%= f.submit %>
  <% end %>

</div>

app/views/pets/edit.html.erb
THIS IS THE EDIT
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<ol>
  <% @pets.each do |pet| %>
    <%= link_to pet_path(pet) do %>
      <li><%= pet.name %></li>
    <% end %>
  <% end %>
</ol>

app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<h1>This is <%= @pet.name %>'s show page</h1>

<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Destroy", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?" } %>